# Generated by Django 3.2.4 on 2021-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_path',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
